id: ADEF33972
title: Prayer to the Successive Lives of the Great Trulshik 'Destroyer of Delusion'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:00:42.042532
  last_modified_at: 2022-03-01 01:00:42.042541
